# Generated by Django 5.2.8 on 2025-11-28 21:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0003_message_parent_message_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['receiver', 'is_read', 'timestamp'], name='messaging_m_receive_24dc6a_idx'),
        ),
    ]
