# Generated by Django 5.2.7 on 2025-11-13 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_conversationparticipant_alter_message_options_and_more'),
    ]

    operations = [
    ]
